### ISSUE TITLE
Ribbon UI and functionnalities review

### ISSUE THREAD

**Issue by NPavie** [daisy/word-save-as-daisy#22]
With latest updates and the new development plan, we might need to rework the ribbon to better reflect what should be done by the add in, and what should be done using native MS Word functionalities.

The following issues provide a preliminary list of changes required:
- [ ] #16 : we should remove the footnote button from the ribbon and check if the manual redirect user to Word footnotes and end notes documentation
- [ ] #4 : We need to rename the ribbon, possibly after finding a new name for the addin
- [ ] #5 : Updates the screen shot with the updated ribbon UI

A review of the current ribbon functionalities is required, checking if they still work as expected and if there is a matching native word functionality.
